import * as React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import {
  Download01Icon,
  ArrowRight01Icon,
  CheckmarkCircle01Icon,
  FileCodeIcon,
  SparklesIcon,
} from "@hugeicons/core-free-icons";
import { HaloIcon } from "@/components/icons/halo-icon";

export const metadata: Metadata = {
  title: "Registry Architecture — Documentation | HaloUI",
  description:
    "How HaloUI distributes components using the shadcn registry specification, URL installation, and custom registry schemas.",
};

export default function RegistryDocPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      <div className="space-y-3 border-b border-black/[0.06] dark:border-white/[0.06] pb-8">
        <div className="text-xs font-mono uppercase tracking-widest text-stone-400">
          Architecture / Distribution
        </div>
        <h1 className="text-3xl sm:text-5xl font-bold tracking-tight text-stone-950 dark:text-white">
          shadcn Registry Architecture
        </h1>
        <p className="text-base text-stone-600 dark:text-stone-400 leading-relaxed font-normal">
          HaloUI is fully aligned with the official shadcn registry architecture. Rather than publishing an opaque NPM package, components distribute directly into your codebase where you own and modify every line.
        </p>
      </div>

      {/* Distribution Models */}
      <section className="space-y-6">
        <h2 className="text-xl font-bold tracking-tight text-stone-900 dark:text-white">
          Distribution Models
        </h2>

        <div className="space-y-4">
          <div className="p-6 rounded-2xl border border-black/[0.08] dark:border-white/[0.08] bg-black/[0.015] dark:bg-white/[0.02] space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-semibold text-stone-900 dark:text-white">
                1. Direct URL Installation
              </h3>
              <span className="font-mono text-xs text-stone-400">Supported Today</span>
            </div>
            <p className="text-xs text-stone-500 leading-relaxed">
              Every component endpoint provides a full JSON registry item compliant with <code className="font-mono">https://ui.shadcn.com/schema/registry-item.json</code>.
            </p>
            <div className="p-3 rounded-lg bg-black/5 dark:bg-white/10 font-mono text-xs text-stone-800 dark:text-stone-200">
              <code>pnpm dlx shadcn@latest add https://haloui.dev/r/button.json</code>
            </div>
          </div>

          <div className="p-6 rounded-2xl border border-black/[0.08] dark:border-white/[0.08] bg-black/[0.015] dark:bg-white/[0.02] space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-semibold text-stone-900 dark:text-white">
                2. Custom Registry Namespace
              </h3>
              <span className="font-mono text-xs text-stone-400">Multi-Component Workflow</span>
            </div>
            <p className="text-xs text-stone-500 leading-relaxed">
              Add HaloUI as a named registry in your project&apos;s <code className="font-mono">components.json</code>:
            </p>
            <div className="p-3 rounded-lg bg-black/5 dark:bg-white/10 font-mono text-xs text-stone-800 dark:text-stone-200">
              <pre>{`"registries": {
  "@haloui": "https://haloui.dev/r/{name}.json"
}`}</pre>
            </div>
            <p className="text-xs text-stone-500">
              Then install with simple namespace commands: <code className="font-mono">pnpm dlx shadcn add @haloui/button</code>.
            </p>
          </div>
        </div>
      </section>

      {/* Inspecting Live JSON */}
      <section className="space-y-4 pt-8 border-t border-black/[0.06] dark:border-white/[0.06]">
        <h2 className="text-xl font-bold tracking-tight text-stone-900 dark:text-white">
          Inspect Live Registry Payload
        </h2>
        <p className="text-sm text-stone-600 dark:text-stone-400 leading-relaxed">
          You can inspect the live registry endpoint generated by this Next.js app right now:
        </p>
        <div className="flex items-center gap-3">
          <a
            href="/r/button.json"
            target="_blank"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-black/10 dark:border-white/10 bg-black/[0.03] dark:bg-white/[0.05] hover:bg-black/[0.06] dark:hover:bg-white/[0.1] text-xs font-mono text-stone-800 dark:text-stone-200 transition-colors"
          >
            <HaloIcon icon={FileCodeIcon} size={15} />
            <span>Open /r/button.json</span>
          </a>
        </div>
      </section>
    </div>
  );
}
